### ISSUE TITLE
TL Encoder: Option values can be zero, TL Encoder doesn't support it

### ISSUE THREAD

**Issue by ololosha228** [xelaj/mtproto#47]
Copied from #44 

@airani wrote:

for example I called this request

```go
res, err := client.MessagesGetHistory(&telegram.MessagesGetHistoryParams{
		Peer: &telegram.InputPeerChannel{
			ChannelId:  channel.TelegramID,
			AccessHash: channel.AccessHash,
		},
		Limit: 100,
                OffsetId: 12,
	})
```
and I want messages after messageID `12` but this code actually sent `OffsetId:12` and `OffsetDate:0` and TL priority with `OffsetDate` and this request not worked correctly!

but with my custom changes that works correctly like this:

```go 
type MessagesGetHistoryParams struct {
	Peer        InputPeer
	OffsetId   *int32
	OffsetDate *int32
        // ....
}

func (e *MessagesGetHistoryParams) Encode() []byte {
	err := validator.New().Struct(e)
	dry.PanicIfErr(err)

	buf := serialize.NewEncoder()
	buf.PutUint(e.CRC())
	buf.PutRawBytes(e.Peer.Encode())


        if e.OffsetDate != nil {
                buf.PutInt(*e.OffsetId)
        }
	if e.OffsetDate != nil {
		buf.PutInt(*e.OffsetDate)
	}
        // ...
}
```

## What's the porblem:

Imagine, that we have some method like `DoSomethingWithMediaFile(mediaID int, zeroIfYouNeedSave int)`, where   `zeroIfYouNeedSave` is optional (encoded in bitflags, `flag:#` in schema)

so, how you can put exact zero value in `zeroIfYouNeedSave` when if this argument is zero, bitflag set that this option is nil?

## TODO:

* [ ] post here list of ALL methods or structs, which are has this situation
* [ ] decide, do we need add this feature to tl parser or just add this methods in `methods_specific.go` file
* [ ] additional: contact with @levlam, he's knowing more about issues like this one.
